import {
  getAccessoriesSvg,
  createOwnAvatar,
  OPTIONS,
  getDefaultAvatar,
  getEyeBrowsSvg,
  getEyesSvg,
  getFacialHair,
  getListOfOptions,
  getMouthSvg,
  getSkinTon,
  AvatarsTypes,
  getClothingGraphicsSvg,
  getClothingSvg,
  getTop,
} from './utils/utils';
export {
  getClothingGraphicsSvg,
  getClothingSvg,
  getTop,
  getAccessoriesSvg,
  createOwnAvatar,
  OPTIONS,
  getDefaultAvatar,
  getEyeBrowsSvg,
  getEyesSvg,
  getFacialHair,
  getListOfOptions,
  getMouthSvg,
  getSkinTon,
  AvatarsTypes,
};
export {default as Avataars} from './components/Avataars';
