import {
  createOwnAvatar,
  OPTIONS,
  getDefaultAvatar,
  getEyesSvg,
  getListOfOptions,
  getMouthSvg,
  getBeardSvg,
  getEarringsSvg,
  getEyeBrowsSvg,
  getFrecklesSvg,
  getGlasses,
  getHair,
  getHairAccessories,
  getHead,
  getNose,
  getBaseColor,
  MicahType,
} from './utils/utils';
export {
  getBeardSvg,
  getEarringsSvg,
  getEyeBrowsSvg,
  getFrecklesSvg,
  getGlasses,
  getHair,
  getHairAccessories,
  getHead,
  getNose,
  createOwnAvatar,
  OPTIONS,
  getDefaultAvatar,
  getEyesSvg,
  getListOfOptions,
  getMouthSvg,
  getBaseColor,
  MicahType,
};
export {default as Micah} from './components/Micah';
