import {
  createOwnAvatar,
  OPTIONS,
  getDefaultAvatar,
  getEyesSvg,
  getListOfOptions,
  getBeardSvg,
  NotionistsTypes,
  getBodySvg,
  getBrowsSvg,
  getGestureSvg,
  getGlassesSvg,
  getHairSvg,
  getLipsSvg,
  getNoseSvg,
} from './utils/utils';
export {
  getBeardSvg,
  createOwnAvatar,
  OPTIONS,
  getDefaultAvatar,
  getEyesSvg,
  getListOfOptions,
  NotionistsTypes,
  getBodySvg,
  getBrowsSvg,
  getGestureSvg,
  getGlassesSvg,
  getHairSvg,
  getLipsSvg,
  getNoseSvg,
};
export { default as Notionists } from './components/Notionists';
