import {
  createOwnAvatar,
  OPTIONS,
  getDefaultAvatar,
  getEyesSvg,
  getFacialHair,
  getListOfOptions,
  getMouthSvg,
  getSkinTon,
  BigEarsType,
  getCheeksSvg,
  getFaceSvg,
  getHairSvg,
  getNoseSvg,
  getSideBurnSvg,
} from './utils/utils';
export {
  getNoseSvg,
  getSideBurnSvg,
  getCheeksSvg,
  getFaceSvg,
  getHairSvg,
  createOwnAvatar,
  OPTIONS,
  getDefaultAvatar,
  getEyesSvg,
  getFacialHair,
  getListOfOptions,
  getMouthSvg,
  getSkinTon,
  BigEarsType,
};
export {default as BigEars} from './components/BigEars';
